import type { MockDealForMarketplace, UrgencyTag } from "@/lib/types-marketplace";

const T = (tags: UrgencyTag[]) => tags;

const mattMatch = (lines: string[]) => lines;

/**
 * Tiered example campaigns (UI-only) — pairs with `messages-mock-data` threads where `messageThreadId` is set.
 */
export const MOCK_MARKETPLACE_DEALS: MockDealForMarketplace[] = [
  {
    id: "mock-alley-mac-ksu",
    messageThreadId: "mock-thread-alley-mac",
    title: "Alley Mac — BOGO specialty mac bowls",
    businessName: "Alley Mac",
    location: "Kent, OH",
    category: "Food & local",
    payout: 85,
    payoutLabel: "BOGO",
    description: "Best mac in Kent. Limited weekly deal.",
    requirements:
      "In store only. Order two specialty mac bowls; code SUMMER at checkout or say “Matthew sent me” / show this screen. Staff may ask to see this screen.",
    phone: "(330) 548-9215",
    instagram: "@alleymackent",
    website: "https://alleymackent.com",
    tags: T(["HOT", "NEW", "EASY", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "This week — while supplies last; ask staff for details",
    matchReasons: mattMatch([
      "Local Kent / KSU — built for students and game-day traffic",
      "BOGO specialty bowls — high perceived value, easy to explain at the counter",
      "Promoted by Matt Maxey (Kent State Football) — trusted on-campus signal",
    ]),
    tier: "mid",
    fomo: { slotsLeft: 6, expiresInHours: 144, viewingCount: 28 },
    premiumSpotlight: {
      variant: "alley-mac",
      heroImage: "/deals/alley-mac-hero.png",
      headline: "BUY 1 GET 1 FREE",
      subtext: "This week only",
      redemptionLine: "Say ‘Matthew sent me’ OR show this screen",
      code: "SUMMER",
      codeDescription: "Code SUMMER — BOGO specialty mac & cheese bowls this week.",
      urgencyBar: "🔥 23 Kent students used this deal today",
      socialProof: "Used by 47+ students this week",
      promoterName: "Matt Maxey",
      promoterTag: "Kent State Football",
      endsAt: "2026-05-02T23:59:59.000Z",
    },
  },
  /* —— Low tier —— */
  {
    id: "mock-cle-coffee",
    messageThreadId: "mock-thread-cle-coffee",
    title: "Coffee shop morning rush",
    businessName: "CLE Coffee Co.",
    location: "Cleveland, OH",
    category: "Food & local",
    payout: 50,
    payoutLabel: "$50",
    description:
      "Simple local collab: one honest story about your pre-practice or study grind with our drink in frame. We want real, not perfect.",
    requirements: "1 Instagram story (15s), tag @clecoffee, post between 7–10am on an agreed day.",
    phone: "(216) 555-0101",
    instagram: "@clecoffee",
    tags: T(["NEW", "EASY", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "This week — pick a morning that fits your schedule",
    matchReasons: mattMatch([
      "Your Cleveland metro activity overlaps this cafe’s target radius",
      "Quick story format = low time cost, fast payout",
      "Strong fit: campus + training-day routines",
    ]),
    tier: "entry",
    fomo: { slotsLeft: 4, expiresInHours: 18, viewingCount: 12 },
  },
  {
    id: "mock-campus-drip",
    messageThreadId: "mock-thread-campus-drip",
    title: "Campus fit check — drop day",
    businessName: "Campus Drip",
    location: "Cleveland, OH",
    category: "Apparel",
    payout: 75,
    payoutLabel: "$75",
    description:
      "Show how you style our campus line between classes and practice. We want authentic ‘real student athlete’ energy.",
    requirements: "1 feed outfit post + tag @campusdrip; use the campaign hashtag we send you.",
    phone: "(440) 555-0202",
    instagram: "@campusdrip",
    tags: T(["NEW", "TRENDING", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "Content within 7 days of ship",
    matchReasons: mattMatch([
      "Apparel + short-form is your highest-engagement lane historically",
      "Local brand = faster shipping and same-day DMs",
      "High match: your audience skews college-age in-region",
    ]),
    tier: "entry",
    fomo: { viewingCount: 7, expiresInHours: 36 },
  },
  {
    id: "mock-smoothie-bar",
    messageThreadId: "mock-thread-smoothie-bar",
    title: "Smoothie Bar — post-workout pair",
    businessName: "Blend & Go",
    location: "Akron, OH",
    category: "Food & wellness",
    payout: 100,
    payoutLabel: "$100",
    description:
      "Two short posts: one before training, one after, featuring the smoothie flavor we assign. Show the routine, not a commercial.",
    requirements: "2 posts (feed or reels) + save to highlights for 48h; tag the location + @blendgo.akron.",
    phone: "(330) 555-8844",
    instagram: "@blendgo.akron",
    tags: T(["EASY", "NEW", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "Shoot window: next 10 days",
    matchReasons: mattMatch([
      "Wellness + training content matches your performance brand",
      "Two-post arc fits a ‘day in the life’ pattern your audience likes",
      "Brands in this band often renew if completion is fast",
    ]),
    tier: "entry",
    fomo: { slotsLeft: 5, viewingCount: 4 },
  },
  {
    id: "mock-north-thread",
    messageThreadId: "mock-thread-north-thread",
    title: "Spring drop — studio + street",
    businessName: "North Thread Co.",
    location: "Cleveland, OH",
    category: "Clothing",
    payout: 95,
    payoutLabel: "$95",
    description:
      "Layer our spring line in a real day: class, training, and one night-out fit. We want clean tags, no forced posing — your audience should feel the fabric in motion.",
    requirements: "1 carousel (3+ photos) + 1 reel; tag @norththreadco; include campaign hashtag in caption.",
    phone: "(216) 555-4480",
    instagram: "@norththreadco",
    tags: T(["NEW", "TRENDING", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "Ship window: next 8 days (content + tag within 48h of delivery)",
    matchReasons: mattMatch([
      "Clothing is your fastest-converting category this month in our match engine",
      "Local fulfillment = you can shoot this week without travel drag",
      "High match: your style content outperforms category median on saves",
    ]),
    tier: "entry",
    fomo: { slotsLeft: 3, expiresInHours: 12, viewingCount: 5 },
  },
  /* —— Mid tier —— */
  {
    id: "mock-elite-cuts",
    messageThreadId: "mock-thread-elite-cuts",
    title: "Barbershop line-out promo",
    businessName: "Elite Cuts",
    location: "Cleveland, OH",
    category: "Lifestyle",
    payout: 125,
    payoutLabel: "$125",
    description:
      "Drive referrals with a clean before/after or ‘game day cut’ vibe. We’ll give you a unique code to share in the caption.",
    requirements: "1 feed/reel + referral code in caption; 30-day tracking window.",
    phone: "(216) 555-3030",
    instagram: "@elitecuts",
    tags: T(["HOT", "TRENDING", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "Post by next Friday",
    matchReasons: mattMatch([
      "Gameday + grooming is a high-trust category for your demo",
      "Referral model rewards reach without needing huge follower counts",
      "Strong geo match: same city cluster as your prior collabs",
    ]),
    tier: "mid",
    fomo: { viewingCount: 9, expiresInHours: 20 },
  },
  {
    id: "mock-local-event",
    messageThreadId: "mock-thread-local-event",
    title: "Local event — fill the room",
    businessName: "Summit City Nights",
    location: "Cleveland, OH",
    category: "Events",
    payout: 200,
    payoutLabel: "$200",
    description:
      "We need 20+ people on the list and two hype posts in the 48h window before doors. You’re the local voice that makes it feel legit.",
    requirements: "2 posts + show proof of 20+ RSVPs/attendance via our check-in list.",
    phone: "(440) 555-6622",
    instagram: "@summitcitynights",
    website: "https://summitcity.example.com",
    tags: T(["NEW", "ENDING_SOON", "HIGH_MATCH"]),
    easyTask: false,
    timeline: "Event date TBD within 2 weeks",
    matchReasons: mattMatch([
      "Event promos favor athletes who can move real bodies, not just impressions",
      "You’ve shown you can post with urgency — that maps to event windows",
      "Ticket/RSVP offers stack well with your messaging cadence this month",
    ]),
    tier: "mid",
    fomo: { slotsLeft: 2, viewingCount: 11, expiresInHours: 30 },
  },
  {
    id: "mock-prime-hydration-gym",
    messageThreadId: "mock-thread-prime-hydration",
    title: "Prime Hydration Gym — content sprint",
    businessName: "Prime Hydration Gym",
    location: "Cleveland, OH",
    category: "Fitness",
    payout: 300,
    payoutLabel: "$300",
    description:
      "Show a real training moment with our bottles in frame. We want authentic gym energy, not a polished ad read — post-workout clip works best.",
    requirements: "1 workout clip (15–45s) + tag the brand; allow 6 months organic repost rights.",
    phone: "(216) 555-1142",
    instagram: "@primehydrationgym",
    tags: T(["NEW", "EASY", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "Post by this Friday 6pm ET; we can boost the best take",
    matchReasons: mattMatch([
      "Workout content is a top-performing format in your feed mix",
      "Local gym radius matches your home training narrative",
      "AI match score: 94 — based on category + region + recency of posts",
    ]),
    tier: "mid",
    fomo: { viewingCount: 6, expiresInHours: 24 },
  },
  /* —— High tier —— */
  {
    id: "mock-sports-bar",
    messageThreadId: "mock-thread-sports-bar",
    title: "Game day bar takeover",
    businessName: "The Post Sports Bar",
    location: "Akron, OH",
    category: "Hospitality",
    payout: 400,
    payoutLabel: "$400",
    description:
      "Be the face of our game-day promo: pre-game energy, table shots of the special, and a quick in-venue hello so fans know where to go after the buzzer.",
    requirements: "1 in-person appearance (2h) + 2 stories + 1 feed post; tag venue + special.",
    phone: "(330) 555-7712",
    instagram: "@thepostakron",
    tags: T(["HOT", "TRENDING", "HIGH_MATCH"]),
    easyTask: false,
    timeline: "Next home game window — we’ll confirm jersey night date",
    matchReasons: mattMatch([
      "Game-day hospitality is a strong fit for your in-person charisma in stories",
      "Payout band matches brands that expect attendance + content",
      "High match: you’ve engaged sports-adjacent audiences in-region before",
    ]),
    tier: "high",
    fomo: { viewingCount: 8, expiresInHours: 48 },
  },
  {
    id: "mock-nut-house",
    messageThreadId: "mock-thread-nut-house",
    title: "Nightlife promo @ Nut House",
    businessName: "Nut House",
    location: "Austin, TX",
    category: "Nightlife",
    payout: 500,
    payoutLabel: "$500",
    description:
      "Pack the room for our signature DJ night. You bring the crowd and the content; we handle the experience. High visibility on a weekend slot with clear deliverables.",
    requirements:
      "Bring 50+ people through the door, post 2 Instagram stories + 1 reel during promo week, tag @nuthouseatx, age 21+.",
    phone: "(512) 555-9821",
    instagram: "@nuthouseatx",
    website: "https://nuthouse.example.com",
    tags: T(["HOT", "TRENDING", "ENDING_SOON", "HIGH_MATCH"]),
    easyTask: false,
    timeline: "This week — main event Friday 10pm–2am; stories due Thu",
    matchReasons: mattMatch([
      "Nightlife collabs favor creators who can drive real foot traffic, not just views",
      "Your message response time is in the top tier — brands pay more for that reliability",
      "Match boost: high payout + your profile strength unlocks this tier",
    ]),
    tier: "high",
    fomo: { slotsLeft: 3, expiresInHours: 12, viewingCount: 5 },
  },
  {
    id: "mock-fuel-perform",
    messageThreadId: "mock-thread-fuel-perform",
    title: "Fuel Perform — short-form blitz",
    businessName: "Fuel Perform",
    location: "United States (remote)",
    category: "Supplements",
    payout: 600,
    payoutLabel: "$600",
    description:
      "Three punchy TikToks that show your real routine and why you trust the stack. We care about hook rate and authentic voice — not studio polish.",
    requirements: "3 TikToks (20–45s) + link in bio for 7 days; disclose partnership; no medical claims.",
    phone: "(800) 555-3301",
    instagram: "@fuelperform",
    website: "https://fuelperform.example.com",
    tags: T(["TRENDING", "HOT", "HIGH_MATCH"]),
    easyTask: true,
    timeline: "Drafts due in 5 business days; live after quick brand OK",
    matchReasons: mattMatch([
      "Supplement vertical rewards consistent short-form + compliance-safe language",
      "You’re a strong match for 3+ piece packages with clear deadlines",
      "Top payout tier — unlocked because your deal velocity is trending up",
    ]),
    tier: "high",
    fomo: { slotsLeft: 2, viewingCount: 8, expiresInHours: 72 },
  },
];
